export enum FishingHoleType {
  // Limsa Lominsa Upper Decks
  LIMSA_LOMINSA_UPPER_DECKS = 36,

  // Limsa Lominsa Lower Decks
  LIMSA_LOMINSA_LOWER_DECKS = 35,

  // Middle La Noscea
  ZEPHYR_DRIFT = 37,
  ROGUE_RIVER = 39,
  WEST_AGELYSS_RIVER = 40,
  SUMMERFORD = 38,
  NYM_RIVER = 41,
  WOAD_WHISPER_CANYON = 42,

  // Lower La Noscea
  THE_MOURNING_WIDOW = 43,
  MORABY_BAY = 44,
  CEDARWOOD = 45,
  OSCHONS_TORCH = 47,
  CANDLEKEEP_QUAY = 49,
  MORABY_DRYDOCKS = 46,
  EMPTY_HEART = 50,
  THE_SALT_STRAND = 48,
  BLIND_IRON_MINES = 97,

  // Eastern La Noscea
  SOUTH_BLOOSHORE = 51,
  COSTA_DEL_SOL = 52,
  NORTH_BLOODSHORE = 53,
  RHOTANO_SEA_PRIVATEER_FORECASTLE = 107,
  RHOTANO_SEA_PRIVATEER_STERNCASTLE = 108,
  HIDDEN_FALLS = 54,
  EAST_AGELYSS_RIVER = 55,
  RAINCATCHER_GULLY = 56,
  THE_JUGGERNAUT = 57,
  RED_MANTIS_FALLS = 58,
  NORTH_ISLE_OF_ENDLESS_SUMMER = 156,

  // Western La Noscea
  SWIFTPERCH = 59,
  SKULL_VALLEY = 60,
  THE_BREWERS_BEACON = 64,
  HALFSTONE = 61,
  ISLES_OF_UMBRA_NORTHSHORE = 62,
  THE_SHIP_GRAVEYARD = 65,
  SAPSA_SPAWNING_GROUNDS = 101,
  ISLES_OF_UMBRA_SOUTHSHORE = 63,
  REAVER_HIDE = 102,

  // Upper La Noscea
  OAKWOOD = 66,
  FOOL_FALLS = 67,
  BRONZE_LAKE_SHALLOWS = 98,
  NORTHEAST_BRONZE_LAKE = 68,

  // Outer La Noscea
  THE_LONG_CLIMB = 99,
  NORTHWEST_BRONZE_LAKE = 155,

  // Mist
  MIST = 104,

  // New Gridania
  JADEITE_FLOOD = 90,
  LOWER_BLACK_TEA_BROOK = 91,

  // Old Gridania
  WHISPERING_GORGE = 81,
  UPPER_BLACK_TEA_BROOK = 100,

  // Central Shroud
  THE_VEIN = 2,
  THE_MIRROR = 3,
  EVERSCHADE = 4,
  HOPESEED_POND = 5,
  HAUKKE_MANOR = 92,

  // East Shroud
  SWEETBLOOM_PIER = 6,
  SPRINGRIPPLE_BROOK = 8,
  SANCTUM_OF_THE_TWELVE = 10,
  VERDANT_DROP = 7,
  SYLPHLANDS = 9,

  // South Shroud
  UPPER_HATHOEVA_RIVER = 11,
  LOWER_HATHOEVA_RIVER = 13,
  EAST_HATHOEVA_RIVER = 14,
  MIDDLE_HATHOEVA_RIVER = 12,
  GOBLINBLOOD = 15,
  ROOTSLAKE = 16,
  URTHS_GIFT = 17,

  // North Shroud
  MURMUR_RILLS = 18,
  FALLGOURD_FLOAT = 19,
  PROUD_CREEK = 20,
  LAKE_TAHTOTL = 21,

  // The Lavender Beds
  THE_LAVENDER_BEDS = 105,

  // Western Thanalan
  NOPHICAS_WELLS = 72,
  THE_FOOTFALLS = 73,
  VESPER_BAY = 70,
  CRESCENT_COVE = 71,
  THE_SILVER_BAZAAR = 69,
  CAPE_WESTWIND = 74,
  MOONDRIP = 103,
  PARATAS_PEACE = 95,

  // Central Thanalan
  UPPER_SOOT_CREEK = 75,
  LOWER_SOOT_CREEK = 76,
  THE_CLUTCH = 96,
  THE_UNHOLY_HEIR = 77,

  // Eastern Thanalan
  NORTH_DRYBONE = 78,
  SOUTH_DRYBONE = 79,
  YUGRAM_RIVER = 80,
  THE_BURNING_WALL = 82,

  // Southern Thanalan
  BURNT_LIZARD_CREEK = 83,
  ZAHARAK = 84,
  FORGOTTEN_SPRINGS = 85,
  SAGOLII_DESERT = 86,
  SAGOLII_DUNES = 87,

  // Northern Thanalan
  BLUEFOG = 89,
  CERULEUM_FIELD = 88,

  // Goblet
  THE_GOBLET = 106,

  // Coerthas Central Highlands
  COERTHAS_RIVER = 26,
  DANIFFEN_PASS = 31,
  THE_NAIL = 28,
  DRAGONHEAD_LATRINES = 30,
  EXPLORATORY_ICE_HOLE = 32,
  THE_WEEPING_SAINT = 29,
  SNOWCLOAK = 33,
  SEA_OF_CLOUDS = 34,
  WITCHDROP = 27,

  // Coerthas Western Highlands
  RIVERSMEET = 109,
  GREYTAIL_FALLS = 110,
  UNFROZEN_POND = 111,
  CLEARPOOL = 112,
  DRAGONSPIT = 113,
  SOUTH_BANEPOOL = 114,
  ASHPOOL = 115,
  WEST_BANEPOOL = 116,

  // Mor Dhona
  NORTH_SILVERTEAR = 22,
  THE_DEEP_TANGLE = 25,
  SINGING_SHARDS = 93,
  RATHEFROST = 23,
  THE_TANGLE = 24,
  THE_NORTH_SHARDS = 94,

  // The Sea of Clouds
  VOOR_SIAN_SIRAN = 135,
  THE_EDDIES = 136,
  CLOUDTOP = 137,
  THE_BLUE_WINDOW = 138,
  MOK_OOGL_ISLAND = 139,

  // Azys Lla
  ALPHA_QUADRANT = 140,
  AETHEROCHEMICAL_SPILL = 141,
  HYPERSTELLAR_DOWNCONVERTER = 142,
  DELTA_QUADRANT = 143,
  THE_PAPPUS_TREE = 144,
  THE_HABISPHERE = 145,
  THE_FLAGSHIP = 146,

  // The Dravanian Forelands
  THE_HUNDRED_THROES = 117,
  WHILOM_RIVER = 118,
  THE_SMOLDERING_WASTES = 119,
  THE_IRON_FEAST = 120,
  MOURN = 121,
  WEST_MOURN = 122,
  ANYX_OLD = 123,
  HALO = 124,

  // The Dravanian Hinterlands
  THALIAK_RIVER = 125,
  QUICKSPILL_DELTA = 126,
  UPPER_THALIAK_RIVER = 127,
  MIDDLE_THALIAK_RIVER = 128,

  // The Churning Mists
  EIL_TOHM = 129,
  GREENSWARD = 130,
  WESTON_WATERS = 131,
  LANDLORD_COLONY = 132,
  SOHM_AL_SUMMIT = 133,
  THARL_OOM_KHASH = 134,

  // Rhalgr's Reach
  UPPER_MIRAGE_CREEK = 182,
  RHALGRS_REACH = 183,
  THE_OUTER_FIST = 184,

  // The Fringes
  TIMMON_BECK = 185,
  DIMWOLD = 186,
  THE_COMETS_TAIL = 187,
  THE_VELODYNA_RIVER = 188,
  MIRAGE_CREEK = 189,

  // The Peaks
  GRYMM_ENID = 190,
  THE_SLOW_WASH = 191,
  HEATHER_FALLS = 192,
  THE_EPHOR = 193,
  THE_BULLS_BATH = 194,
  THE_ARMS_OF_MEED = 195,

  // The Lochs
  LOCH_SELD = 196,

  // Kugane
  KUGANE_PIERS = 157,

  // Shirogane
  SHIROGANE = 197,
  THE_SILVER_CANAL = 198,

  // The Ruby Sea
  THE_RUBY_PRICE = 158,
  HELLS_LID = 159,
  THE_ISLE_OF_BEKKO = 160,
  SHOAL_ROCK = 161,
  ONOKORO = 162,
  ISARI = 163,
  THE_ISLE_OF_ZEKKI = 164,

  // Yanxia
  THE_HERONS_NEST = 165,
  THE_HERONS_WAY = 166,
  NAMAI = 167,
  THE_ONE_RIVER_EAST = 172,
  THE_ONE_RIVER_WEST = 173,
  PLUM_SPRING = 174,
  PRISM_CANYON = 169,
  PRISM_LAKE = 168,
  MERCANTILE_DOCKS = 171,
  DOMA_CASTLE = 170,

  // The Azim Steppe
  NEM_KHAAL = 175,
  HAK_KHAAL = 176,
  UPPER_YAT_KHAAL = 177,
  AZIM_KHAAT = 178,
  TAO_KHAAL = 179,
  LOWER_YAT_KHAAL = 180,
  DOTHARL_KHAA = 181,
}
