export enum LocationType {
  // La Noscea
  LIMSA_LOMINSA_UPPER_DECKS,
  LIMSA_LOMINSA_LOWER_DECKS,
  MIDDLE_LA_NOSCEA,
  LOWER_LA_NOSCEA,
  EASTERN_LA_NOSCEA,
  WESTERN_LA_NOSCEA,
  UPPER_LA_NOSCEA,
  OUTER_LA_NOSCEA,
  MIST,

  // The Black Shroud
  NEW_GRIDANIA,
  OLD_GRIDANIA,
  CENTRAL_SHROUD,
  EAST_SHROUD,
  SOUTH_SHROUD,
  NORTH_SHROUD,
  THE_LAVENDER_BEDS,

  // Thanalan
  ULDAH_STEPS_OF_NALD,
  ULDAH_STEPS_OF_THAL,
  WESTERN_THANALAN,
  CENTRAL_THANALAN,
  EASTERN_THANALAN,
  SOUTHERN_THANALAN,
  NORTHERN_THANALAN,
  GOBLET,

  // Coerthas
  FOUNDATION,
  THE_PILLARS,
  THE_FIRMAMENT,
  COERTHAS_CENTRAL_HIGHLANDS,
  COERTHAS_WESTERN_HIGHLANDS,
  EMPYREUM,

  // Mor Dhona
  MOR_DHONA,

  // Abalathia's Spine
  THE_SEA_OF_CLOUDS,
  AZYS_LLA,

  // Dravania
  IDYLLSHIRE,
  THE_DRAVANIAN_FORELANDS,
  THE_DRAVANIAN_HINTERLANDS,
  THE_CHURNING_MISTS,

  // Gyr Abania
  RHALGRS_REACH,
  THE_FRINGES,
  THE_PEAKS,
  THE_LOCHS,

  // Hingashi
  KUGANE,
  SHIROGANE,

  // Othard
  THE_RUBY_SEA,
  YANXIA,
  THE_AZIM_STEPPE,
  THE_DOMAN_ENCLAVE,
}
